import { describe, expect, it } from "vitest";
import { existsSync, readFileSync } from "node:fs";

// THE PHASE 1 RUNTIME GATE.
//
// RESEARCH.md rates SQLite feature availability at LOW confidence (assumption A6)
// and `sdk.requests.get(id)` readability as assumption A7 — "the worst possible
// failure shape", because a reload lag means the consumer silently drops the
// NEWEST artifacts, which is the half nobody notices. scripts/phase1/runtime-answers.sh
// answers both by measurement; this file is what stops either answer regressing
// quietly.
//
// FAIL, NEVER SKIP, and name the remedy in every message — the doctrine
// tests/go-no-go.spec.ts sets. An absent or unreadable artifact must fail here
// rather than pass vacuously.

const ANSWERS = ".planning/phases/01-skeleton-persistence-compatibility/results/runtime-answers.json";
const EXPECTED_CAIDO_VERSION = "0.57.1";
const MIN_SQLITE = "3.24.0";
const REMEASURE = "re-run `bash scripts/phase1/runtime-answers.sh`";

function loadJson(path: string): any {
  const raw = readFileSync(path, "utf8");
  try {
    return JSON.parse(raw);
  } catch (err) {
    throw new Error(`${path} is not valid JSON: ${(err as Error).message}`);
  }
}

/** Three-segment numeric comparison. A string compare gets 3.9.0 vs 3.24.0
 *  backwards, and that is exactly the boundary this gate sits on. */
function cmpVersion(a: string, b: string): number {
  const seg = (v: string) => String(v).split(".").slice(0, 3).map((s) => Number(s));
  const x = seg(a);
  const y = seg(b);
  for (let i = 0; i < 3; i++) {
    const xi = x[i] ?? 0;
    const yi = y[i] ?? 0;
    if (xi !== yi) return xi - yi;
  }
  return 0;
}

describe("Phase 1 runtime answers artifact", () => {
  it("exists — Open Questions 1 and 2 have no other answer", () => {
    expect(existsSync(ANSWERS), `${ANSWERS} missing — ${REMEASURE}`).toBe(true);
  });

  const d = existsSync(ANSWERS) ? loadJson(ANSWERS) : null;

  it("parses and carries both scenarios", () => {
    expect(d, `${ANSWERS} did not parse — ${REMEASURE}`).not.toBeNull();
    expect(
      Object.keys(d?.scenarios ?? {}).sort(),
      `${ANSWERS} is missing a scenario — ${REMEASURE}`,
    ).toEqual(["reload_after_burst", "reload_immediate"]);
  });

  // Two SEPARATE assertions, on purpose and for two different failures. The first
  // catches a result recorded against the stale 0.55.3 that owns PATH on this
  // machine. The second catches an expectation quietly moved to match whatever
  // happened to be measured — which is why editing `expected_version` to match a
  // wrong `reported_version` does not rescue the run.
  it("was measured against the build every Phase 0 threshold belongs to", () => {
    expect(
      d?.reported_version,
      `${ANSWERS}: expected_version does not match reported_version. Do not edit the ` +
        `file — ${REMEASURE} against the app-bundle binary.`,
    ).toBe(d?.expected_version);
    expect(
      d?.reported_version,
      `${ANSWERS}: reported_version is not ${EXPECTED_CAIDO_VERSION}. Bare \`caido-cli\` ` +
        `on PATH resolves to a stale 0.55.3; every Phase 1 script must use ` +
        `$P1_CAIDO_BIN from scripts/phase1/env.sh. ${REMEASURE}.`,
    ).toBe(EXPECTED_CAIDO_VERSION);
  });
});

describe("Open Question 1 — SQLite inside sdk.meta.db()", () => {
  const d = existsSync(ANSWERS) ? loadJson(ANSWERS) : null;
  const v = d?.sqlite_version;

  it("is recorded as a three-part version string", () => {
    expect(
      typeof v === "string" && /^\d+\.\d+\.\d+$/.test(v),
      `${ANSWERS}: sqlite_version is ${JSON.stringify(v)}, not a three-part version ` +
        `string. It is read inside Caido with SELECT sqlite_version(); ${REMEASURE}.`,
    ).toBe(true);
  });

  it(`is at least ${MIN_SQLITE} — the upsert strategy has NO FALLBACK below it`, () => {
    expect(
      cmpVersion(String(v), MIN_SQLITE),
      `${ANSWERS}: SQLite inside Caido reports ${JSON.stringify(v)}, which is below ` +
        `${MIN_SQLITE}. THE ENTIRE PHASE 1 STORAGE DESIGN RESTS ON ` +
        `\`ON CONFLICT ... DO UPDATE\`, which requires SQLite >= ${MIN_SQLITE} (2018), ` +
        `AND THERE IS NO FALLBACK. This is not a test to relax: the schema design must ` +
        `change — every write becomes a read-then-write pair on a driver with no ` +
        `transaction primitive — and that redesign must land BEFORE plan 01-04 ` +
        `proceeds. Do not edit this file to make the gate pass.`,
    ).toBeGreaterThanOrEqual(0);
  });

  it("records ON CONFLICT DO UPDATE as EXERCISED, not inferred", () => {
    expect(
      d?.features?.on_conflict_do_update,
      `${ANSWERS}: features.on_conflict_do_update is ` +
        `${JSON.stringify(d?.features?.on_conflict_do_update)} ` +
        `(${d?.features?.on_conflict_do_update_reason ?? "no reason recorded"}). The flag ` +
        `must be true and must come from actually running the upsert more than once — ` +
        `a version string does not prove the driver compiled the syntax. ${REMEASURE}.`,
    ).toBe(true);
  });
});

describe("Open Question 2 — sdk.requests.get(id) reload readability", () => {
  const d = existsSync(ANSWERS) ? loadJson(ANSWERS) : null;
  const scenarios: Array<[string, any]> = Object.entries(d?.scenarios ?? {});

  it("both scenarios were actually measured", () => {
    expect(scenarios.length, `${ANSWERS} carries no scenarios — ${REMEASURE}`).toBe(2);
    for (const [name, s] of scenarios) {
      expect(
        s?.measured,
        `${ANSWERS}: scenario ${name} was not measured (${s?.reason ?? "no reason recorded"}). ` +
          `A missing scenario is null with a reason, never a zero — ${REMEASURE}.`,
      ).toBe(true);
    }
  });

  it.each(scenarios)("%s reloaded every enqueued entry", (name: string, s: any) => {
    // Non-vacuity FIRST: a scenario that processed nothing satisfies
    // `reloadMissing === 0` trivially and would pass having proven nothing.
    expect(
      s?.processed,
      `${ANSWERS}: scenario ${name} processed 0 artifacts, so its reload figures prove ` +
        `nothing. Check that a project was selected — with none selected the proxy fails ` +
        `every request and the hook never fires. ${REMEASURE}.`,
    ).toBeGreaterThan(0);

    expect(
      s?.reloadMissing,
      `${ANSWERS}: scenario ${name} recorded ${s?.reloadMissing} missing reloads. ` +
        `sdk.requests.get(id) was NOT readable for every enqueued event, which means ` +
        `CORE-05's reload model needs a BOUNDED RETRY and the consumer's shape changes: ` +
        `assumption A7 has failed. Do not silently tolerate a non-zero value here.`,
    ).toBe(0);

    expect(
      s?.reloadHit,
      `${ANSWERS}: scenario ${name} reloaded ${s?.reloadHit} entries but processed ` +
        `${s?.processed}. Every processed entry must correspond to a successful reload, ` +
        `or the consumer is writing rows from something other than a reload.`,
    ).toBe(s?.processed);
  });

  it("the burst scenario genuinely buffered rather than keeping pace trivially", () => {
    const burst = d?.scenarios?.reload_after_burst;
    expect(
      burst?.peakQueueDepth,
      `${ANSWERS}: reload_after_burst recorded a peak queueDepth of ` +
        `${JSON.stringify(burst?.peakQueueDepth)} ` +
        `(${burst?.peakQueueDepthReason ?? "sampled externally while the load ran"}). ` +
        `A depth of 0 or 1 means the consumer kept pace and the scenario never created ` +
        `the queue delay Open Question 2 is about — so its reload figures answer the ` +
        `easy case only. ${REMEASURE}.`,
    ).toBeGreaterThan(1);
  });

  it("records the worst-case event-to-reload delta the burst produced", () => {
    const burst = d?.scenarios?.reload_after_burst;
    expect(
      typeof burst?.maxEventToReloadMs,
      `${ANSWERS}: reload_after_burst has no maxEventToReloadMs. The measured worst-case ` +
        `delay between an intercept event and its successful reload is the number ` +
        `CORE-05 is designed against; ${REMEASURE}.`,
    ).toBe("number");
    expect(burst.maxEventToReloadMs).toBeGreaterThanOrEqual(0);
  });
});
