// packages/engine/src/hostile.fixture.ts — THE adversarial corpus. One module.
//
// ===========================================================================
// ONE FIXTURE, FOUR SURFACES. A SECOND ONE IS THE DEFECT THIS PREVENTS.
// ===========================================================================
// 05-UI-SPEC.md § "UI Considerations" carries six `backstop` rows and four of
// them name this corpus: the findings table's 256-character cell cap, the
// evidence panel's 2,048-character cap, the export dialog's formula
// neutralisation, and — when Phase 4 unblocks them — the suppressions list and
// the findings-projection preview. 05-VALIDATION.md § "Wave 0 Requirements"
// states the requirement in four words: one fixture, four assertions.
//
// The reason it is one module and not four copies is not tidiness. Two fixtures
// is how two surfaces come to assert different things about the same attack,
// and how the one that is wrong stays wrong: nobody diffs two test corpora.
// Every consumer imports from here, and every consumer asserts it covered
// `HOSTILE_CASE_IDS` IN FULL — a fixture that grows a case some spec silently
// iterates past is a fixture that proves less each time it is extended.
//
// CONSUMERS, named so a reader knows what an edit here reaches:
//   packages/engine/src/sanitise.spec.ts   (this plan)
//   packages/engine/src/csv.spec.ts        (this plan)
//   the frontend hostile-render spec       (plan 05-05)
//   the export serialiser's spec           (plan 05-11)
//   the suppressions list and the projection preview inherit it UNCHANGED when
//   Phase 4 unblocks those surfaces — extend this array, do not fork it.
//
// ===========================================================================
// EVERYTHING HERE IS A STRING LITERAL
// ===========================================================================
// `packages/backend/src/outbound-prohibition.spec.ts` walks BOTH source roots
// with the TypeScript parser, and `packages/engine/src` is one of them. This
// file is not a `.spec.ts`, so it IS scanned. That is fine and is the point of
// saying so here: the payloads below are STRING LITERALS, never call
// expressions, so the markup and script payloads read as data to an AST walk
// exactly as they must read as data to a renderer. Do not "improve" a case into
// executable code.
//
// Adversarial characters are written as escapes rather than literals. A literal
// C0 control or RIGHT-TO-LEFT OVERRIDE in a source file is invisible in every
// diff and every review tool, and this corpus is entirely about characters that
// are invisible.

import { TABLE_CELL_MAX_GRAPHEMES } from "./sanitise";

/**
 * One adversarial case.
 *
 * `why` names the attack in one line and is not decoration: a failing
 * `it.each` prints the id, and the id is only useful next to the reason the
 * case exists.
 */
export type HostileCase = {
  readonly id: string;
  readonly why: string;
  readonly value: string;
};

/** 4 MiB, generated by repetition rather than written out. */
const MULTI_MEGABYTE = "A".repeat(4 * 1024 * 1024);

export const HOSTILE_CASES: readonly HostileCase[] = Object.freeze([
  {
    id: "markup-element-and-handler",
    why: "R1 — an element plus an attribute-borne handler; must render as text, never as markup",
    value: '<img src=x onerror=alert(1)><b onmouseover="alert(2)">hover</b>',
  },
  {
    id: "script-element",
    why: "R1 — a script element; the payload body is deliberately inert because shipped-source gates parse this file",
    value: "<script>alert(1)</script>",
  },
  {
    id: "csv-formula-equals",
    why: "R3 — the canonical Excel command payload, led by =",
    value: "=cmd|' /C calc'!A0",
  },
  {
    id: "csv-lead-plus",
    why: "R3 — the same payload led by +, the second dangerous lead",
    value: "+cmd|' /C calc'!A0",
  },
  {
    id: "csv-lead-minus",
    why: "R3 — led by -, which also reads as a negative number and so looks benign",
    value: "-cmd|' /C calc'!A0",
  },
  {
    id: "csv-lead-at",
    why: "R3 — led by @, the lead most often missed because it is not an operator",
    value: "@SUM(1+1)*cmd|' /C calc'!A0",
  },
  {
    id: "csv-lead-tab",
    why: "R3 / T-05-14 — a TAB lead; a spreadsheet skips leading whitespace, so this must not hide the = behind it",
    value: "\t=cmd|' /C calc'!A0",
  },
  {
    id: "csv-lead-cr",
    why: "R3 / T-05-14 — a CR lead, the same trick and the sixth dangerous lead",
    value: "\r=cmd|' /C calc'!A0",
  },
  {
    id: "c0-control-run",
    why: "R2 step 1 — a run across the C0 range including NUL, BEL, ESC and US",
    value: "a\u0000b\u0007c\u001Bd\u001Fe",
  },
  {
    id: "c1-control-run",
    why: "R2 step 1 — the C1 range, which a strip written as [\\x00-\\x1F] alone would miss entirely",
    value: "a\u007Fb\u0080c\u0085d\u009Fe",
  },
  {
    id: "bidi-override-hostname-reversal",
    why: "R2 step 2 / T-05-11 — renders as evil.com in the hostname column the operator triages on",
    value: "\u202Emoc.live\u202C",
  },
  {
    id: "bidi-isolate-sequence",
    why: "R2 step 2 — isolates rather than overrides; the range a strip written for U+202x alone would miss",
    value: "\u2066host\u2067name\u2068spoof\u2069",
  },
  {
    id: "four-byte-grapheme",
    why: "UISEC-03 — THUMBS UP + FITZPATRICK MODIFIER; two code points, four UTF-16 code units, one grapheme. A naive slice leaves a lone surrogate",
    value: "\u{1F44D}\u{1F3FD} deploy key rotated",
  },
  {
    id: "combining-mark-stack",
    why: "UISEC-03 — one base carrying three combining marks; truncation must never cut between them",
    value: "e\u0301\u0302\u0303vil.com",
  },
  {
    id: "embedded-newlines-and-tabs",
    why: "UISEC-03 — a value with embedded newlines and tabs; removed by the table path, shown as escapes by the panel, and never able to grow a fixed 32px row",
    value: "line one\nline two\tcolumn two\r\nline three",
  },
  {
    id: "multi-megabyte-single-line",
    why: "T-05-12 — 4 MiB on one line; must truncate without freezing the renderer and without being rebuilt in memory",
    value: MULTI_MEGABYTE,
  },
  {
    id: "exactly-table-cell-cap",
    why: "UISEC-03 boundary — exactly the cell cap; must come back unchanged with shown === total",
    value: "c".repeat(TABLE_CELL_MAX_GRAPHEMES),
  },
  {
    id: "one-over-table-cell-cap",
    why: "UISEC-03 boundary — one past the cell cap; the off-by-one that a >= / > slip turns into a silent truncation or a silent overflow",
    value: "d".repeat(TABLE_CELL_MAX_GRAPHEMES + 1),
  },
  {
    id: "url-with-credential-segment",
    why: "SEC-04 adjacency — a URL-shaped value carrying userinfo and a query token; it is DISPLAYED, never offered as a destination (R1)",
    value:
      "https://operator:EXAMPLE-NOT-A-SECRET@internal.example.test/v1/admin?api_key=EXAMPLE-NOT-A-SECRET&next=/",
  },
  {
    id: "empty",
    why: "The degenerate case — must survive every path as an empty value rather than as a missing one, so a CSV column keeps its position",
    value: "",
  },
]);

/**
 * The ids, frozen and in declaration order.
 *
 * A consuming spec asserts the set of ids it EXERCISED equals this list. That
 * is the difference between "iterates the fixture" and "iterates the part of
 * the fixture it happened to write a case for" — and it is what makes adding a
 * case here fail every consumer until each one accounts for it, which is the
 * intended cost.
 */
export const HOSTILE_CASE_IDS: readonly string[] = Object.freeze(
  HOSTILE_CASES.map((hostileCase) => hostileCase.id),
);
