// packages/engine/src/sourcemap/map-fixture.ts — THE sourcemap corpus. One module.
//
// ===========================================================================
// ONE FIXTURE, THREE CONSUMERS. A SECOND ONE IS THE DEFECT THIS PREVENTS.
// ===========================================================================
// The reason it is one module and not three copies is not tidiness. Two fixtures
// is how two surfaces come to assert different things about the same attack, and
// how the one that is wrong stays wrong: nobody diffs two test corpora. Every
// consumer imports from here, and every consumer asserts it covered the
// relevant `*_CASE_IDS` array IN FULL — a fixture that grows a case some spec
// silently iterates past is a fixture that proves less each time it is extended.
//
// CONSUMERS, named so a reader knows what an edit here reaches:
//   tests/corpus-maps.spec.ts             (this plan — the fixture's own gate)
//   the MAP-05 hostile-map suite          (plan 07-02)
//   the retained traversal-sink gate      (plan 07-03)
// Extend these arrays; do not fork them.
//
// ===========================================================================
// WHY THE BYTES LIVE HERE AND NOT UNDER `corpus/`
// ===========================================================================
// RESEARCH § O-03 says to commit the map fixtures under `corpus/maps/` with a
// sha256 gate. THAT INSTRUCTION IS NOT FOLLOWED, and the reason is mechanical:
// `corpus/` is gitignored IN ITS ENTIRETY (`.gitignore:9` — check it with
// `git check-ignore -v corpus/`). Bytes written there do not survive a clean
// checkout, so a fixture placed there is a claim rather than an artifact.
//
// The corpus splits by SIZE across the two homes that ARE tracked:
//
//   LARGE real maps (megabyte scale, needed only by the D-10 probe) live in
//   `scripts/phase7/fetch-maps.sh` with committed SHA-256 hashes, in the
//   `scripts/spike/fetch-corpus.sh` idiom. The script and the hashes are the
//   reproducible artifact; the ~37 MB of vendor JSON is not.
//
//   SMALL hostile and structural fixtures — needed by CI on EVERY COMMIT, with
//   NO NETWORK — live HERE as string literals, in the `hostile.fixture.ts`
//   idiom. That is why this file exists at all.
//
// ===========================================================================
// EVERYTHING HERE IS A STRING LITERAL, AND EVERY ADVERSARIAL CHARACTER IS AN
// ESCAPE SEQUENCE
// ===========================================================================
// `packages/backend/src/outbound-prohibition.spec.ts` walks BOTH source roots
// with the TypeScript parser and `packages/engine/src` is one of them. This file
// is not a `.spec.ts`, so it IS scanned. The payloads below are STRING LITERALS,
// never call expressions, so a hostile map reads as data to an AST walk exactly
// as it must read as data to a parser. Do not "improve" a case into executable
// code, and do not replace a document with `JSON.stringify` of an object — the
// point of several cases is text a JSON serialiser would never produce.
//
// Adversarial characters are written as ESCAPES rather than literals. A literal
// C0 control or RIGHT-TO-LEFT OVERRIDE in a source file is invisible in every
// diff and every review tool, and this corpus is entirely about characters that
// are invisible.
//
// The `value` of a case is the document or the label AS DELIVERED — the bytes a
// parser or a renderer would actually receive — not a parsed object. Several
// cases (the XSSI prefix, the truncated document) are not valid JSON at all, and
// that is the case.

import {
  EVIDENCE_PANEL_MAX_GRAPHEMES,
  TABLE_CELL_MAX_GRAPHEMES,
} from "../sanitise";

/**
 * One sourcemap fixture case.
 *
 * `why` names the hazard in one line and is not decoration: a failing
 * `it.each` prints the id, and the id is only useful next to the reason the
 * case exists. Deliberately the same three-field shape as `HostileCase` in
 * `hostile.fixture.ts`, so a consumer that iterates one can iterate the other.
 */
export type MapFixtureCase = {
  readonly id: string;
  readonly why: string;
  readonly value: string;
};

/** 4 MiB, generated by repetition rather than written out — `MULTI_MEGABYTE`'s idiom. */
const FOUR_MIB_OF_SOURCE = "A".repeat(4 * 1024 * 1024);

/**
 * A million source labels, generated rather than written out.
 *
 * One character each, so the whole array costs roughly the same 4 MiB the
 * `hostile.fixture.ts` precedent already pays once. The hazard is the COUNT, not
 * the content: a map may legally declare any number of sources, and D-09 writes
 * a derived-source row and a sighting row per source.
 */
const MILLION_LABELS = new Array<string>(1_000_000).fill('"a"').join(",");

/**
 * A JSON value nested 800 levels deep, past the measured bracket limit.
 *
 * SPIKE-06 bisected the stack boundary on this exact runtime: brackets last
 * parsed at 710 levels and failed at 718; parentheses last parsed at 246 and
 * failed at 250 [VERIFIED: SPIKE-06.json `nesting_depth` rows]. Those figures
 * were measured against the JS PARSER rather than against `JSON.parse`, which is
 * precisely why this is a fixture and not an assumption — the failure is
 * expected to be a CATCHABLE `RangeError` (SPIKE-06's `failure_class` is
 * `catchable-stack-throw` at every failing depth and the host survived all 18
 * probes), and a consumer must prove that rather than trust it.
 */
const DEEP_NEST = "[".repeat(800) + "]".repeat(800);

/**
 * Structural hostility — the map shapes a target can legally or illegally serve.
 *
 * Each `value` is a COMPLETE DOCUMENT as delivered.
 */
export const HOSTILE_MAP_CASES: readonly MapFixtureCase[] = Object.freeze([
  {
    id: "sources-content-absent",
    why: "Pitfall 3 — `sourcesContent` is OPTIONAL in ECMA-426; the map is announced and parses, and yields no recoverable source. That is NOT a failure and must not read as one (UI-09)",
    value:
      '{"version":3,"file":"app.js","sources":["src/a.ts","src/b.ts"],"names":[],"mappings":"AAAA"}',
  },
  {
    id: "sources-content-shorter-than-sources",
    why: "Pitfall 3 — the spec conditions on `sourcesContentCount > index`, so the array may be SHORT. Iterate `sources` and guard on the content length; never iterate `sourcesContent` and index into `sources`",
    value:
      '{"version":3,"file":"app.js","sources":["src/a.ts","src/b.ts","src/c.ts"],"sourcesContent":["const a=1;"],"names":[],"mappings":"AAAA"}',
  },
  {
    id: "sources-content-null-entry",
    why: 'Pitfall 3 — "entries may be null if some original sources should be retrieved by name". Skip index i; never write a row for a source it cannot produce',
    value:
      '{"version":3,"file":"app.js","sources":["src/a.ts","src/b.ts"],"sourcesContent":["const a=1;",null],"names":[],"mappings":"AAAA"}',
  },
  {
    id: "sources-null-entry",
    why: 'Pitfall 3 — `sources` entries may THEMSELVES be null ("null if the source name is not known") while the CONTENT is still recoverable. A null label stores as SQL NULL and the display tree needs an unnamed-source label at that index',
    value:
      '{"version":3,"file":"app.js","sources":[null,"src/b.ts"],"sourcesContent":["const anon=1;","const b=2;"],"names":[],"mappings":"AAAA"}',
  },
  {
    id: "sections-index-map",
    why: "Pitfall 5 — an INDEX map has no top-level `sources` at all. Read `sections` BEFORE `sources`, or a map with hundreds of sources reports zero",
    value:
      '{"version":3,"file":"bundle.js","sections":[{"offset":{"line":0,"column":0},"map":{"version":3,"file":"a.js","sources":["src/a.ts"],"sourcesContent":["const a=1;"],"names":[],"mappings":"AAAA"}},{"offset":{"line":10,"column":0},"map":{"version":3,"file":"b.js","sources":["src/b.ts"],"sourcesContent":["const b=2;"],"names":[],"mappings":"AAAA"}}]}',
  },
  {
    id: "sections-nested",
    why: "Pitfall 5 / D-13 — MUST BE REFUSED. ECMA-426 defines a section's `map` as a complete source map and index maps DO NOT NEST, so the recursion bound is exactly 1 BY SPECIFICATION. The fixture proves the parser ENFORCES that rather than trusting the input",
    value:
      '{"version":3,"file":"bundle.js","sections":[{"offset":{"line":0,"column":0},"map":{"version":3,"file":"inner.js","sections":[{"offset":{"line":0,"column":0},"map":{"version":3,"file":"a.js","sources":["src/a.ts"],"sourcesContent":["const a=1;"],"names":[],"mappings":"AAAA"}}]}}]}',
  },
  {
    id: "sections-unsorted-overlapping",
    why: 'Pitfall 5 — the spec says sections "shall be sorted by starting position and the represented sections shall not overlap". A SHALL is what a hostile map violates. Must not crash; the ordering is input, not an invariant',
    value:
      '{"version":3,"file":"bundle.js","sections":[{"offset":{"line":40,"column":0},"map":{"version":3,"file":"b.js","sources":["src/b.ts"],"sourcesContent":["const b=2;"],"names":[],"mappings":"AAAA"}},{"offset":{"line":10,"column":0},"map":{"version":3,"file":"a.js","sources":["src/a.ts"],"sourcesContent":["const a=1;"],"names":[],"mappings":"AAAA"}},{"offset":{"line":20,"column":0},"map":{"version":3,"file":"c.js","sources":["src/c.ts"],"sourcesContent":["const c=3;"],"names":[],"mappings":"AAAA"}}]}',
  },
  {
    id: "sections-map-null",
    why: "Pitfall 5 — a section whose `map` is null. `section.map.sources` throws on a document that is otherwise well-formed JSON, so the guard belongs on the member and not on the parse",
    value:
      '{"version":3,"file":"bundle.js","sections":[{"offset":{"line":0,"column":0},"map":null},{"offset":{"line":10,"column":0},"map":{"version":3,"file":"b.js","sources":["src/b.ts"],"sourcesContent":["const b=2;"],"names":[],"mappings":"AAAA"}}]}',
  },
  {
    id: "xssi-prefix",
    why: 'Pitfall 6 — ECMA-426 permits a server to prepend `)]}\'` through end-of-line and the fetch algorithm strips it. Strip by startsWith + indexOf(newline), NEVER a regex. Scoped to HTTP(S) delivery, so it should never appear inside a data: URI — and "should never occur" is not a property of target-controlled input',
    value:
      ")]}'\n" +
      '{"version":3,"file":"app.js","sources":["src/a.ts"],"sourcesContent":["const a=1;"],"names":[],"mappings":"AAAA"}',
  },
  {
    id: "deep-nested-past-stack-limit",
    why: "T-07-03 — a JSON value nested 800 levels, past the 710-bracket boundary SPIKE-06 bisected on this runtime (246 for parens). The measured failure class is `catchable-stack-throw` and the host survived all 18 probes, so the requirement is CATCH AND RECORD, never crash the instance",
    value:
      '{"version":3,"file":"app.js","sources":["src/a.ts"],"sourcesContent":["const a=1;"],"names":[],"mappings":"AAAA","x_defminer_nest":' +
      DEEP_NEST +
      "}",
  },
  {
    id: "million-tiny-sources",
    why: "MAP-06 / D-09 — a map declaring 1,000,000 one-character sources. Legal, and 781 sources is a REAL bundle (monaco), so the hazard is not the shape but the AGGREGATE: D-09 writes a derived-source row and a sighting row per source, and `SOURCE_ROWS_PER_MAP_MAX` is the bound that refuses this. `sourcesContent` is absent so the case is about the COUNT alone",
    value:
      '{"version":3,"file":"app.js","sources":[' +
      MILLION_LABELS +
      '],"names":[],"mappings":"AAAA"}',
  },
  {
    id: "single-giant-sources-content",
    why: "T-05-12 / O-02 — one 4 MiB source with no line structure at all. The opposite hazard to the case above: one row, unbounded per-row cost. `packages/frontend/src/safety/display.ts` measured what the wrong call on a 4 MiB single-line value costs on the real surface — a 37,395 ms scroll",
    value:
      '{"version":3,"file":"app.js","sources":["src/huge.ts"],"sourcesContent":["' +
      FOUR_MIB_OF_SOURCE +
      '"],"names":[],"mappings":"AAAA"}',
  },
  {
    id: "non-ascii-round-trip",
    why: "Pitfall 4 — a POUND SIGN, an EM DASH and a CJK character in recovered source. `atob` returns a latin1 binary string and splits each multi-byte UTF-8 sequence into separate code units; `JSON.parse` still SUCCEEDS because the corruption is inside string values. Nothing throws and the operator reads wrong source. This case round-trips to a different sha256 under the wrong primitive — MEASURED so in the D-10 probe at all four ladder points",
    value:
      '{"version":3,"file":"app.js","sources":["src/i18n.ts"],"sourcesContent":["// price: \\u00a3100 \\u2014 see \\u8aac\\u660e\\nexport const p = 100;"],"names":[],"mappings":"AAAA"}',
  },
]);

/**
 * The `sources` LABELS a map may legally carry — the display and traversal axis.
 *
 * The first twenty-two are SPIKE-12's `path_resolution` corpus VERBATIM, with
 * ids matching its `variant` names so the provenance is one grep away
 * (`.planning/phases/00-runtime-reality-check/results/SPIKE-12.json`). SPIKE-12's
 * own subject — filesystem containment — is gone under D-17, but the STRING
 * CORPUS survives and now serves three purposes at once: D-12's retained
 * traversal proof (a static gate that no `sources` entry reaches a path-like
 * sink), O-08's display-tree normaliser, and the two documented `path.normalize`
 * CORRUPTION cases that are the direct evidence for "must not call `node:path`" —
 * `unicode-rtl-override` normalises to `defminer-escape.txt` with the RTL run
 * CONSUMED and the `..` climbing, and `trailing-dots-spaces` carries its trailing
 * whitespace into the resolved path.
 *
 * `benign-control` is the LEGAL CONTROL: a corpus in which every case fires
 * proves only that the check fires.
 */
export const SOURCES_LABEL_CASES: readonly MapFixtureCase[] = Object.freeze([
  {
    id: "relative-traversal",
    why: "SPIKE-12 #1 — escapes via resolve; the prefix rule REJECTS",
    value: "../../../../../../etc/defminer-escape.txt",
  },
  {
    id: "relative-traversal-encoded",
    why: "SPIKE-12 #2 — percent-encoded separators; the prefix rule ACCEPTS, which is the point",
    value: "..%2f..%2f..%2fdefminer-escape.txt",
  },
  {
    id: "absolute-posix",
    why: "SPIKE-12 #3 — an absolute POSIX path; escapes via resolve",
    value: "/tmp/defminer-absolute-escape.txt",
  },
  {
    id: "absolute-posix-etc",
    why: "SPIKE-12 #4 — absolute into /etc; escapes via resolve",
    value: "/etc/defminer-escape.txt",
  },
  {
    id: "windows-drive",
    why: "SPIKE-12 #5 — a Windows drive letter, which POSIX resolve treats as an ordinary segment",
    value: "C:\\Windows\\Temp\\defminer-escape.txt",
  },
  {
    id: "windows-unc",
    why: "SPIKE-12 #6 — a UNC path; `normalize` rewrites the leading double backslash",
    value: "\\\\server\\share\\defminer-escape.txt",
  },
  {
    id: "windows-reserved-device",
    why: "SPIKE-12 #7 — a reserved DOS device name with no extension",
    value: "CON",
  },
  {
    id: "windows-reserved-device-ext",
    why: "SPIKE-12 #8 — a reserved DOS device name wearing a .js extension",
    value: "NUL.js",
  },
  {
    id: "protocol-webpack",
    why: "SPIKE-12 #9 — the single most common REAL `sources` shape in the wild, and it is a URL and not a path",
    value: "webpack:///./src/app.js",
  },
  {
    id: "protocol-file",
    why: "SPIKE-12 #10 — a file: URL naming an absolute target",
    value: "file:///etc/defminer-escape.txt",
  },
  {
    id: "protocol-http",
    why: "SPIKE-12 #11 — an http: URL. D-01 refuses every fetch, so this must never become one",
    value: "http://evil.example/app.js",
  },
  {
    id: "null-byte",
    why: "SPIKE-12 #12 — a NUL byte truncating a path in any C API behind the runtime; escapes via resolve. Written as \\u0000 because a literal NUL is invisible in every diff",
    value: "safe.js\u0000/../../../etc/defminer-escape.txt",
  },
  {
    id: "unicode-nfc",
    why: "SPIKE-12 #13 — NFC. Pairs with #14: the two render IDENTICALLY and are different strings, which is the duplicate-label case for the display tree",
    value: "caf\u00e9/app.js",
  },
  {
    id: "unicode-nfd",
    why: "SPIKE-12 #14 — NFD, the same label decomposed. Escaped rather than literal so the combining mark is visible in review",
    value: "cafe\u0301/app.js",
  },
  {
    id: "case-lower",
    why: "SPIKE-12 #15 — pairs with #16 on a case-insensitive filesystem: two distinct labels, one target",
    value: "srcdir/app.js",
  },
  {
    id: "case-upper",
    why: "SPIKE-12 #16 — the same label upper-cased",
    value: "SRCDIR/app.js",
  },
  {
    id: "unicode-fullwidth",
    why: "SPIKE-12 #17 — FULLWIDTH FULL STOP (U+FF0E) pairs reading as `..` to a human and not to a normaliser",
    value: "\uff0e\uff0e/\uff0e\uff0e/defminer-escape.txt",
  },
  {
    id: "unicode-rtl-override",
    why: "SPIKE-12 #18 / O-08 — a documented `path.normalize` CORRUPTION case: it normalises to `defminer-escape.txt`, the RTL run CONSUMED and the `..` climbing. Direct evidence for the ban on `node:path` here",
    value: "sub/\u202eresrc\u202c/../../defminer-escape.txt",
  },
  {
    id: "trailing-dots-spaces",
    why: "SPIKE-12 #19 / O-08 — the second `path.normalize` corruption case: the trailing whitespace is RETAINED into the resolved path. Escapes via resolve",
    value: "sub/../../defminer-escape.txt   ",
  },
  {
    id: "empty",
    why: "SPIKE-12 #20 — the degenerate label. Must survive every path as an empty value rather than a missing one, so a row keeps its index. This is the ONE case whose value is legitimately the empty string",
    value: "",
  },
  {
    id: "dot-only",
    why: "SPIKE-12 #21 — a lone `.`, which normalises to the empty string and so collides with #20 after normalisation while being a different input",
    value: ".",
  },
  {
    id: "benign-control",
    why: "SPIKE-12 #22 — THE LEGAL CONTROL. A corpus in which every case fires proves only that the check fires",
    value: "src/app/index.js",
  },
  {
    id: "four-kilobyte-label",
    why:
      "D-12 / O-02 — THE ONE CLASS SPIKE-12 DOES NOT COVER. CONTEXT.md's D-12 names " +
      '"RTL overrides, NUL bytes, 4 KB labels" and SPIKE-12 has the first two. Sized at ' +
      "4,096 characters, ABOVE both shipped caps (TABLE_CELL_MAX_GRAPHEMES = " +
      String(TABLE_CELL_MAX_GRAPHEMES) +
      ", EVIDENCE_PANEL_MAX_GRAPHEMES = " +
      String(EVIDENCE_PANEL_MAX_GRAPHEMES) +
      "), so the truncation boundary is exercised from both sides in the admit.spec.ts " +
      "idiom. Plan 07-07's SOURCE_LINE_MAX_GRAPHEMES must land BELOW 4,096 for that to " +
      "keep holding, and tests/corpus-maps.spec.ts asserts the two shipped caps do",
    value: "L".repeat(4096),
  },
]);

/**
 * ONE label for BOTH boundary documents, and that is deliberate.
 *
 * Two different labels would make the two skeletons two different lengths, so
 * the pair would no longer differ by exactly one byte at every ceiling — and the
 * off-by-one this pair exists to catch is precisely a one-byte difference. The
 * ids already tell the two cases apart; the label is not what distinguishes them.
 */
const BOUNDARY_LABEL = "src/boundary.ts";

/**
 * The size boundary, as a BUILDER rather than as two eager multi-megabyte strings.
 *
 * WHY A BUILDER, stated because the obvious alternative is two frozen constants.
 * Three reasons, and the third is the one that would otherwise bite:
 *
 *   1. COST. Two ~6 MiB documents built at import time, in a module three plans
 *      import, is 12 MiB per consumer for a case most consumers do not exercise.
 *      `hostile.fixture.ts` pays 4 MiB once and that is already the ceiling this
 *      codebase has agreed to.
 *   2. REACH. Plan 07-02's MAP-05 suite wants the SAME boundary property at a
 *      test size as well as at the real ceiling. A parametric boundary gives
 *      both from one definition; two constants give one and invite a second,
 *      forked, small copy — which is the defect this module's header is about.
 *   3. ORDERING. `MAP_MAX_BYTES` is published by `thresholds.ts` from the D-10
 *      probe artifact. A frozen binding here would make this module depend on a
 *      constant that does not exist until the constants land, which is a
 *      forward reference in the wrong direction: the fixture is the more
 *      primitive thing.
 *
 * THE BOUNDARY IS THE `admit.spec.ts` IDIOM — "accepts at exactly the ceiling
 * and rejects one byte above". Both sides, from one call, so a `>=` / `>` slip
 * cannot pass by exercising only the side it gets right.
 *
 * @param ceilingBytes the refusal boundary under test — `MAP_MAX_BYTES` in
 *   production, any value at or above {@link SIZE_BOUNDARY_MIN_BYTES} in a spec.
 */
export function sizeBoundaryCases(
  ceilingBytes: number,
): readonly MapFixtureCase[] {
  return Object.freeze([
    {
      id: "exactly-map-max-bytes",
      why: `MAP-05 boundary — a decoded map of EXACTLY ${ceilingBytes} bytes. Must be ACCEPTED: the ceiling is inclusive, as PASSIVE_MAX_BYTES is in admit.spec.ts`,
      value: mapOfExactly(ceilingBytes, BOUNDARY_LABEL),
    },
    {
      id: "one-over-map-max-bytes",
      why: `MAP-05 boundary — ${ceilingBytes + 1} bytes, ONE over. Must be REFUSED with a named reason, never truncated: a truncated map decodes to WRONG POSITIONS rather than to an error, which is the quiet-wrongness class every gate in this codebase exists to prevent`,
      value: mapOfExactly(ceilingBytes + 1, BOUNDARY_LABEL),
    },
  ]);
}

/**
 * The smallest boundary `sizeBoundaryCases` can produce.
 *
 * Derived, not chosen: it is the length of the empty-tailed skeleton, so a
 * caller asking for less is asking for a document shorter than its own
 * structure. Exported so a spec can state the floor by name.
 */
export const SIZE_BOUNDARY_MIN_BYTES = skeletonLength(BOUNDARY_LABEL);

function skeleton(label: string, body: string): string {
  // Hand-assembled rather than `JSON.stringify`d so the byte arithmetic below is
  // readable at the point it is relied on, and so key order cannot move under a
  // serialiser change.
  return (
    '{"version":3,"file":"boundary.js","sources":["' +
    label +
    '"],"sourcesContent":["' +
    body +
    '"],"names":[],"mappings":"AAAA"}'
  );
}

function skeletonLength(label: string): number {
  return skeleton(label, "").length;
}

/**
 * A syntactically valid map document of EXACTLY `bytes` bytes.
 *
 * The padding is `"x"` repeated: JSON does not escape it, it is one UTF-8 byte
 * per UTF-16 code unit, and the label is ASCII — so `length` IS the byte count
 * and the arithmetic is exact rather than approximate. "Roughly the ceiling" is
 * not a boundary; the whole value of this pair is that one document is one byte
 * larger than the other.
 */
function mapOfExactly(bytes: number, label: string): string {
  const base = skeletonLength(label);
  const pad = bytes - base;
  if (pad < 0) {
    throw new RangeError(
      `sizeBoundaryCases: cannot build a ${bytes}-byte map — the empty-tailed skeleton is ` +
        `already ${base} bytes. SIZE_BOUNDARY_MIN_BYTES is ${base}.`,
    );
  }
  const doc = skeleton(label, "x".repeat(pad));
  /* istanbul ignore next -- the guard is the point, not a branch to cover */
  if (doc.length !== bytes) {
    throw new RangeError(
      `sizeBoundaryCases: built ${doc.length} bytes, wanted ${bytes}. The padding ` +
        `arithmetic assumes one JSON-unescaped ASCII character per byte.`,
    );
  }
  return doc;
}

/**
 * The ids, frozen and in declaration order.
 *
 * A consuming spec asserts the set of ids it EXERCISED equals these lists. That
 * is the difference between "iterates the fixture" and "iterates the part of the
 * fixture it happened to write a case for" — and it is what makes adding a case
 * here fail every consumer until each one accounts for it, which is the intended
 * cost.
 */
export const HOSTILE_MAP_CASE_IDS: readonly string[] = Object.freeze(
  HOSTILE_MAP_CASES.map((mapCase) => mapCase.id),
);

export const SOURCES_LABEL_CASE_IDS: readonly string[] = Object.freeze(
  SOURCES_LABEL_CASES.map((mapCase) => mapCase.id),
);

/**
 * DERIVED FROM THE BUILDER, at the cheapest size it accepts.
 *
 * Built rather than written out so the ids can never disagree with the cases —
 * the same reason the two arrays above map over their own sources. The size is
 * irrelevant here: only the ids are taken.
 */
export const SIZE_BOUNDARY_CASE_IDS: readonly string[] = Object.freeze(
  sizeBoundaryCases(SIZE_BOUNDARY_MIN_BYTES).map((mapCase) => mapCase.id),
);
